pipelines:
  - name: First_Pipeline_Long_Pipeline_Name_Very_Long
    steps:
      - name: First_Step
        type: Bash
        execution: 
          onExecute:
            - echo "Step 1 shouldnt  sync"
            - sleep 10s
            
      - name: Second_Step
        type: Bash
        configuration:
          inputSteps:
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
            - sleep 5s
            
      - name: Third_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Second_Step
        execution: 
          onExecute:
            - echo "Step 3"
            - sleep 5s
          
      - name: Fourth_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Third_Step
        execution: 
          onExecute:
            - echo "Step 2"
            - sleep 5s
