pipelines:
  - name: First_Pipeline_Long_Pipeline_Name_Very_Long
    steps:
      - name: First_Step
        type: Bash
        configuration:
          integrations:
            - name: simple_mail
        execution: 
          onExecute:
            - echo "Step 1"
            - sleep 1m
            
      - name: Second_Step
        type: Bash
        configuration:
          inputSteps:
            - name: First_Step
        execution: 
          onExecute:
            - echo "Step 2"
            - sleep 5s
            
      - name: Third_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Second_Step
        execution: 
          onExecute:
            - echo "Step 2"
            - sleep 5s
          
      - name: Fourth_Step
        type: Bash
        configuration:
          inputSteps:
            - name: Third_Step
        execution: 
          onExecute:
            - echo "Step 2"
            - sleep 5s
